### ISSUE TITLE
module export changed from 1.3.3 to 1.3.4

### ISSUE THREAD

**Issue by puttpotsawee** [eligrey/FileSaver.js#414]
I used FileSaver 1.3.3 with webpack and react+redux for quite a while.
It works like magic!

However, currently I tried to upgrade it to 1.3.4 and found there's a module changes that cause major problems between the versions.

Previously, this syntax work in react-webpack to import and use FileSaver

```javascript
import FileSaver from "file-saver"

FileSaver.saveAs(blob, "filename.pdf")
```

after 1.3.4, it has to be like this

```javascript
import FileSaver from "file-saver"

FileSaver(blob, "filename.pdf")
```

I suggest changing main API like this should be done in major version like going upward to `1.4.0` instead of minor version `1.3.3`->`1.3.4`

since this will affect those who has
```json
"file-saver": "^1.3.3",
```

like this in `package.json`. NPM will auto increment the version in the later build

Thanks!

**Comment by oleksandrstarov** [comment]
Agree, but such changes should be marked as MAJOR - so version should be 2.0.0.
"^1.3.3" allows updates to 1.9.9 and so, and these updates should be backward compatible.

**Comment by robinfhu** [comment]
Just got the same issue after updating to 1.3.4.  The module exports under a different name now.

**Comment by phantomjinx** [comment]
Tried and failed to get 1.3.4 working using angular 4.

Using the hints above, I can get FileSaver to compile and execute from typescript by doing:

```javascript
import FileSaver from "file-saver";
...
FileSaver(dataBlob, name + fileExt);
```

However, unlike 1.3.3 a browser saveAs window no longer appears and nothing gets saved to the filesystem. Any pointers please?

**Comment by envil** [comment]
Bad versioning wasted my whole day.

**Comment by swftvsn** [comment]
This bit us also, reverted back to 1.3.3 for now.

**Comment by alexgoldstone** [comment]
I use Angular 5... the only way I got things to work was to pin my dependencies to version 1.3.3 and then I could simply do:
```
import { saveAs } from 'file-saver';
...
...
...
saveAs(blob, 'test.pdf');
```

**Comment by r-paredes-bernal** [comment]
@puttpotsawee explained the root cause. Fix: Downgrade the version:

npm install file-saver@1.3.3 --save

**Comment by preekmr** [comment]
Broke the main app flow. Downgrade to 1.3.3 helped.

**Comment by Mrtexx** [comment]
I've tryed to downgrade the version to 1.3.3 yes, but the result was the same. ERROR TypeError: file_saver_1.saveAs is not a function?
Do you have any idea?

**Comment by preekmr** [comment]
@Mrtexx Have you uninstalled and installed again by using **npm install file-saver@1.3.3** ?

**Comment by Domvel** [comment]
`npm i -S file-saver@1.3.3`

**Comment by Mrtexx** [comment]
@preekmr Yes, sure. But in the end, I've tryed to downgrade at version 1.3.0 and I've temporary fixed the problem.

**Comment by acomito** [comment]
`"file-saver": "^1.3.3"`
to
`"file-saver": "1.3.3"`

**Comment by merlosy** [comment]
For those  who want to use `^1.3.3`, I opted for this way :
```ts
    import * as FileSaver from 'file-saver';
    [...]
    FileSaver.saveAs(blob, 'test.pdf');
```
so I can easily mock the `saveAs` method in my test (jasmine):
```ts
    spyOn(FileSaver, 'saveAs').and.stub();
    [...]
    expect(FileSaver.saveAs).toHaveBeenCalled();
```

**Comment by cbettinger** [comment]
Is this going to be fixed or not? I'm stuck with 1.3.3 although current version is 1.3.8.

**Comment by merlosy** [comment]
@cbettinger you can upgrade using my syntax, work well for me. 
But i agree, import/export could be improved.

**Comment by cbettinger** [comment]
Unfortunately my project uses CommonJS imports, not ES6 imports.

**Comment by cbettinger** [comment]
I tried 1.3.8 and this seems to have been fixed without any notice.

**Comment by Ruffio** [comment]
So this issue can be closed?

**Comment by cbettinger** [comment]
I think a confirmation of puttpotsawee or at least another person should be waited for.

**Comment by barbalex** [comment]
I can confirm v1.3.8 works for me.

But surprisingly without changing the signature, so it still is: `fileSaver.saveAs` and not `fileSaver` directly.

I am a little confused because it seems the signature had changed after 1.3.3. But now it has not?

**Comment by cbettinger** [comment]
That's exactly what I have realized today.
