### ISSUE TITLE
not working in opera 12.10

### ISSUE THREAD

**Issue by sfornengo** [eligrey/FileSaver.js#10]
work fine in chromium and firefox but get this error in opera 12.10:
Unhandled Error: 'file.remove' is not a function
